#!/usr/bin/env python

"""
Convert juptyer notebooks to html, markdown, or pdf during git commits

1. convert them to the format(s) and file schema specified in config.ini
    - HTML files will get post-processing to remove rerun visualizer data and store separately
2. commit those newly converted files
"""
import argparse
import configparser
import os
import re
import subprocess

convert_dict = {
    'markdown': {'ext': 'md', 'default': 'no'},
    'html': {'ext': 'html', 'default': 'yes'},
    'pdf': {'ext': 'pdf', 'default': 'no'}
}
CONFIG_LOCATION = 'config.ini'


def create_config():
    """create config file with default output type setting written to {CONFIG_LOCATION}"""
    if os.path.exists(CONFIG_LOCATION):
        return  # if the config already exists, don't overwrite it

    lines = ["[output_types]"]
    for output_type, d in convert_dict.items():
        lines.append('{} = {}'.format(output_type, d['default']))
    lines.append("")
    lines.append("[output_dir]")
    lines.append("path = .rendered/{output_type}")

    with open(CONFIG_LOCATION, "w") as f:
        f.write('\n'.join(lines))


def system(*args, **kwargs):
    """Run system command."""
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out.decode("utf-8")


def system_with_exitcode(*args, **kwargs):
    """Run system command and return an exit code."""
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return proc.returncode


def get_changed_files():
    """Get python files from 'files to commit' git cache list."""
    files = []
    filelist = system('git', 'diff', '--cached', '--name-status').strip()
    for line in filelist.split('\n'):
        if line == '':
            continue
        try:
            action, filename = line.strip().split('\t')
            print(filename)
            if filename.endswith('.ipynb') and action != 'D':
                files.append(filename)
        except Exception:
            raise
    return files


def purge_head_and_extract_data_rrd(html_content, data_dir):
    # Use regex to remove the content within the <head> tag
    content = re.sub('(?<=<head>).*?(?=</head>)', '', html_content, flags=re.DOTALL)

    # Use regex to extract divs with data-rrd attribute and replace the attribute value with a running number
    pattern = re.compile(
        r'<div[^>]*data-rrd="([^"]*)"[^>]*>.*?</div>', re.DOTALL)
    matches = pattern.findall(content)
    for i, match in enumerate(matches, start=1):
        content = content.replace(f'data-rrd="{match}"', f'data-rrd="{i}"', 1)
        with open(f'{data_dir}/{i}.txt', 'w') as f:
            f.write(match)

    # Return the modified content
    return content


def treat_html_file(path):
    # Read the HTML file
    with open(path) as f:
        html_content = f.read()

    file_dir = os.path.dirname(path)
    data_dir = f'{file_dir}/data'
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)

    modified_html = purge_head_and_extract_data_rrd(html_content, data_dir)

    # Write out modified content
    new_file = f'{file_dir}/index.html'
    with open(new_file, 'w') as f:
        f.write(modified_html)

    # Remove original HTML file
    os.remove(path)

    print(f'Successfully wrote modified HTML to {os.path.realpath(new_file)} and data to the "data" directory.')


def convert(files, output_type, output_dir):
    """run nbconvert to {output_type} on list of {files}"""
    converted_paths = []

    for file in files:
        root_dir = os.getcwd()
        file_path = os.path.realpath(file)
        file_dir = os.path.dirname(file_path)
        file_name = os.path.basename(file).split('.')[0]
        os.chdir(file_dir)
        write_dir = os.path.join(os.path.dirname(file_dir), output_dir)
        if not file_dir.endswith("notebooks"):
            notebook_category = os.path.split(file_dir)[1]
            write_dir = os.path.join(write_dir, notebook_category)
        if output_type == 'html':
            write_dir = os.path.join(write_dir, file_name)
        args = ['jupyter', 'nbconvert', '--to']
        args.append(output_type)
        args.append(file_path)
        args.append('--output-dir=%s' % write_dir)
        print(' '.join(args))
        exitcode = system_with_exitcode(*args)
        if output_type == 'html':
            treat_html_file(f"{write_dir}/{file_name}.html")
        os.chdir(root_dir)
        if exitcode == 0:
            converted_paths.append(write_dir)
        else:
            raise Exception(f'nbconvert failed for {file}')

    return converted_paths


def gitadd(file_paths, output_type, output_dir):
    """git add all newly (re)rendered notebook files"""
    add_dirs = []
    for file_path in file_paths:
        # file_dir = os.path.dirname(os.path.realpath(file_path))
        # file_name = os.path.basename(file_path).split('.')[0]
        # add_dir = f'{file_dir}/{output_dir}'
        add_dir = file_path + '*'
        add_dirs.append(add_dir)
    exitcode = system_with_exitcode('git', 'add', *add_dirs)
    if exitcode != 0:
        raise Exception(f'git add failed for {output_dir} with exit code {exitcode}')


def process(files, output_type, output_dir):
    """convert notebooks files to {output_type} and git add the rendered notebook files"""
    output_dir_ext = output_dir.format(output_type=output_type)
    converted_paths = convert(files, output_type, output_dir_ext)
    if len(converted_paths) > 0:
        gitadd(converted_paths, output_type, output_dir_ext)


def main(args):

    if args['all']:
        files = filter(
            lambda x: x.endswith('.ipynb'),
            [f for f in os.listdir('.') if os.path.isfile(f)]
        )
    else:
        print(args['positional'])
        files = [f for f in args['positional'] if f.endswith('.ipynb')]  # get_changed_files()

    if len(files) == 0:
        return

    if args['pdf']:
        process(files, 'pdf', args['output_dir'])
    if args['markdown']:
        process(files, 'markdown', args['output_dir'])
    if args['html']:
        process(files, 'html', args['output_dir'])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Process Config Location")
    parser.add_argument('positional', nargs="*", type=str)
    parser.add_argument('--all', action='store_true')
    try:
        config = configparser.ConfigParser()
        config.read(CONFIG_LOCATION)
        args = vars(parser.parse_args())
        for option in config.options('output_types'):
            args[option] = config.getboolean('output_types', option)
        args['output_dir'] = config.get('output_dir', 'path')
    except configparser.NoSectionError:
        pass
    except Exception as e:
        print(e)
        parser.add_argument('--html', action='store_true')
        parser.add_argument('--markdown', action='store_true')
        parser.add_argument('--pdf', action='store_true')
        args = vars(parser.parse_args())
    main(args)
